### ISSUE TITLE
Remove "Record Last Modified" from display in search results

### ISSUE THREAD

**Issue by cnewallbcgov** [bcgov/ckanext-bcgov#472] opened 2018-03-19 18:31 UTC
This UI enhancement is associated with an objective to reduce screen clutter/noise.  In this case the record last modified is not particularly useful information as it doesn't reflect the date that the data itself was last modified.  

Scope:  removing only from each record's summary in the search results list.

![image.png](https://images.zenhubusercontent.com/5a7c85584b5806bc2bc62b7f/179fd358-9c3f-4c6c-b22c-1287716b2352)

If the change can be squeezed into 1.7.0 then great.  Else, 1.7.1.

Test:  search result list no longer shows this information.

**Comment by dkelsey** [comment] 2018-04-09 17:40
## This is a duplicate of #380.  **Remove redundant words from search results listing**
I'll close #380

**Comment by dkelsey** [comment] 2018-05-02 16:39
Passed in TEST

**Comment by dkelsey** [comment] 2018-05-23 20:10
Verified in PROD

**Closed by dkelsey** 2018-05-23 20:10 UTC
