### ISSUE TITLE
POW does not automatically set resource type

### ISSUE THREAD

**Issue by garrettH3S** [bcgov/ckanext-bcgov#448] opened 2018-02-23 18:33 UTC
Currently the pow does not take a format name to set the ordered resource type. One solution is to create a new metadata field for GEO type resources that holds the resource id. This needs to be added to the URL parameters for opening the POW js module.

**Comment by jeff-at-h3** [comment] 2018-02-27 21:06
duplicate of #401

**Closed by jeff-at-h3** 2018-02-27 21:06 UTC
Labels: bug
