### ISSUE TITLE
update thin header footer style as the blog/engagement site

### ISSUE THREAD

**Issue by ll911** [bcgov/ckanext-bcgov#82] opened 2016-06-22 19:09 UTC
Using this page as a model ... http://engage.gov.bc.ca/govtogetherbc/ make the following changes to the UI: 
1) Remove thin gold vertical bar next to sunrise
2) Remove search magnifying glass.
3) Make div id=header-main shorter
4) Only add the hamburger when page is in mobile view.
5) Drop the standard gov navigation IA from the hamburger menu - just move the catalogue (div.level2navigation and div.level3navigation content to the hamburger icon ).

**Comment by gjlawran** [comment] 2016-06-22 21:44
Using this page as a model ... http://engage.gov.bc.ca/govtogetherbc/ make the following changes to the UI: 
1) Remove thin gold vertical bar next to sunrise
2) Remove search magnifying glass.
3) Make div id=header-main shorter
4) Only add the hamburger when page is in mobile view.
5) Drop the standard gov navigation IA from the hamburger menu - just move the catalogue (div.level2navigation and div.level3navigation content to the hamburger icon ).

**Comment by Mbrownshoes** [comment] 2016-06-28 01:07
linked to CITZEDC-759

**Comment by kfishwick** [comment] 2016-06-28 21:13
Assigning back to Greg to alighn with https://github.com/bcgov/data-fp/issues/32

**Comment by ll911** [comment] 2016-06-30 23:25
@gjlawran any updates?

**Comment by gjlawran** [comment] 2016-07-04 23:39
Confirmed @kfishwick  this should be in the 1.3 release if possible.

Make sure you keep the extra element in the footer ('Tracking').

**Comment by h3devin** [comment] 2016-07-05 17:28
Fixed in https://github.com/bcgov/ckanext-bcgov/pull/103

**Comment by ll911** [comment] 2016-07-05 17:39
@h3devin @kfishwick @gjlawran search box missing in the top right header, and footer height needs adjust.

**Comment by Mbrownshoes** [comment] 2016-07-05 18:18
clicking on the header (above the yellow line) redirects users to the main gov site.

**Comment by h3devin** [comment] 2016-07-05 18:48
@ll911 I can add a search box for desktop/tablet, but I don't think there will be enough room to keep it in mobile (which it looks like the govTogetherBC site does too)

@Mbrownshoes How should this work?  On prod it redirects to the main gov from the logo, and "Data Catalogue" redirects to the catalogue site.  Did you want to mirror that?

**Comment by ll911** [comment] 2016-07-05 18:50
@h3devin search box changed to magnifying glass in mobile mode, see style in http://blog.data.gov.bc.ca/

**Comment by h3devin** [comment] 2016-07-05 18:52
@ll911 Is this search box for the data catalogue or the gov site?

**Comment by ll911** [comment] 2016-07-05 18:54
@h3devin data catalogue

**Comment by h3devin** [comment] 2016-07-05 20:10
Additional updates in https://github.com/bcgov/ckanext-bcgov/pull/105

**Comment by ll911** [comment] 2016-07-05 20:27
@h3devin header looks good, you can remove the "Collapsible footer" like the blog/engagement site
<img width="1215" alt="screen shot 2016-07-05 at 1 25 10 pm" src="https://cloud.githubusercontent.com/assets/11949273/16598738/28f4ab94-42b4-11e6-8545-3b8030298111.png">

**Comment by gjlawran** [comment] 2016-07-05 21:38
This fine as currently delivered. Thanks.

**Comment by ll911** [comment] 2016-07-05 21:40
@gjlawran if you like to accept the current one, we should close this ticket and create new one for footer.

**Comment by gjlawran** [comment] 2016-07-05 21:52
@ll911  I will accept it as code complete - but that move it up to @kfishwick  - would prefer to only close on production verification. 

@h3devin  we will raise another ticket to deal with the height issue for the footer - it wasn't in the list - the list just specified adjusting the header height.

**Closed** 2016-07-12 22:54 UTC
Labels: enhancement
