### ISSUE TITLE
'Download permission' facet fails to list Applications when 'Public' facet set.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#500] opened 2018-04-12 17:22 UTC
# ENV
 `CAT`, `CAD`

### The current behavior in `PROD` is that with the **'Public'** facet activated, **Applications** are listed in search results and the **Dataset types** facet.

# TESTCASE
* log out if you are logged in,  This is only a problem if you are not logged in.
* navigate to the fully qualified `hostname` in either CAT or CAD : do not include `/dataset` as this will not activate the 'Public' **Download permission** facet
* or activate the `Public` **Download permission** facet.
![image](https://user-images.githubusercontent.com/3906047/38693110-ce565adc-3e3a-11e8-9d10-2d1ddda9770d.png)
* scroll down to view the **Dataset types** facet

# EXPECTED
* the **Dataset types** facet will list all 4 dataset types and the facets will have counts representing the number of datasets in that facet.

![image](https://user-images.githubusercontent.com/3906047/38693172-0536fdea-3e3b-11e8-8d0a-49283486f67f.png)

# ACTUAL
![image](https://user-images.githubusercontent.com/3906047/38693218-1c1575e6-3e3b-11e8-8ff5-87a7f64709b8.png)

**Comment by mdunhamwilkie** [comment] 2018-11-13 16:05
This appears to be fixed in CAT.  Moving it to the verify in PROD pipeline.

**Comment by dkelsey** [comment] 2018-11-13 17:27
@mdunhamwilkie This remains an issue.

**Comment by mdunhamwilkie** [comment] 2018-11-13 17:59
@dkelsey I can't reproduce this in CAT. Am I missing something?

**Comment by mdunhamwilkie** [comment] 2018-11-13 20:21
Only an issue if you are not logged in.

**Comment by jachurchill** [comment] 2018-12-11 21:39
@mdunhamwilkie So this issue is interesting, the facet is for download audience, applications cannot be set as downloadable, the reason that there are a couple that work in PROD is likely that they were uploaded by API and have the download audience set, but if you check there you'll see that with the public facet selected 31 Applications show, without 109 show.

If we want to change this we could look into that facet and make it look at another attribute but the facet is currently working as it should

**Closed** 2018-12-13 17:23 UTC
Labels: bug
