### ISSUE TITLE
Editing a resource's resource page edits all resources for the record and not the resource itself.

### ISSUE THREAD

**Issue by dkelsey** [bcgov/ckanext-bcgov#305] opened 2017-03-10 21:56 UTC
*Steps:*

1. As an Editor, navigate to a resource's information page and Click the 'Manage' button.

![screen shot 2017-03-10 at 1 39 52 pm](https://cloud.githubusercontent.com/assets/3906047/23814432/57fad6e6-0598-11e7-9f6b-acf31524b2d4.png)

*Expected:*
I should be take to a page that allows me to edit/manage the particular resource.

![screen shot 2017-03-10 at 1 54 57 pm](https://cloud.githubusercontent.com/assets/3906047/23814655/34aaeb30-0599-11e7-84c4-d281bc9bcfd0.png)

*Actual:*
First I see this:
![screen shot 2017-03-10 at 1 40 07 pm](https://cloud.githubusercontent.com/assets/3906047/23814490/99310914-0598-11e7-9b2a-9759eabdd49c.png)

If I click 'Edit' I'm shown this:
![screen shot 2017-03-10 at 1 40 16 pm](https://cloud.githubusercontent.com/assets/3906047/23814522/b4844fbe-0598-11e7-9bc6-11ff902fc088.png)

When I cancel I remain at the resources Information page.

**Comment by kfishwick** [comment] 2017-03-17 19:02
Duplicate of issue#302?

**Comment by Mbrownshoes** [comment] 2017-12-20 19:25
since we are removing the POW, I will close this ticket.

**Closed by Mbrownshoes** 2017-12-20 19:25 UTC
