### ISSUE TITLE
Gracefully handle situations where the OFI API is not available.  Default would be no download permitted.

### ISSUE THREAD

**Issue by jeff-at-h3** [bcgov/ckanext-bcgov#409] opened 2017-12-20 22:32 UTC
Feedback from Dave (via email thread)
I agree.
 
This is an excellent feature to add, though it needs more definition. 
•         Quickly we want the geo resource page to fail gracefully
•         We don’t want it to fail silently: there should be some mechanism of alerting us that OFI is failing
 
To clarify; this was in regards to what was pointed out in our meeting with H3?  That DLV cannot connect to the BCGW?
 
I’ll explain my understanding of the problem then I’ll raise some questions:
 
How I think it works:
In Delivery, operating in OpenShift:
•         From in the catalogue, when navigating to a resource in a Geographic record, and
•         before the resource page can be displayed,
•         a server side connection of made, through the dwds-ofi API – this connection must be made to determine Authorizations “whether the user has the privilege to view or download the resource”
•         because DLV is running in OpenShift it operates in a distinct network zone. 
•         The Zone is not able to route traffic through to the zone the DWDS is operating in.
•         This is because admins of the network that DWDS is homed in have not granted access.
•         The API call is originating from the CKAN server in OpenShift and it fails, ungracefully.
•         This ungraceful failure is what causes the page to fail horribly.
 
It would be helpful to have this mapped out in a picture and documented so that it’s not just in Leo’s head (if it is)
Do I have this described correctly?

**Comment by jrods** [comment] 2018-01-29 19:04
I have put in place graceful handling of DWDS OFI calls, with ckan debug off, when opening the dialog, it will look like this:
![Screen Shot 2018-01-29 at 11.02.00 AM.png](https://images.zenhubusercontent.com/577aa11dbf93871ccd9d8cfa/a8c214d9-a074-48fd-a6c2-767bfb93b284)

with debugging on (CAD):
![Screen Shot 2018-01-29 at 11.01.14 AM.png](https://images.zenhubusercontent.com/577aa11dbf93871ccd9d8cfa/80e0d7cf-2576-47a5-8c76-8c6c0c0d9353)

**Comment by jrods** [comment] 2018-01-31 23:44
@dkelsey This is now in CAD and can be tested.

Note: when the POW is merged in, to test this issue, you'll have to change the `bcgov.pow.enable_mow` option to `true` in the cad config repo.

**Comment by jeff-at-h3** [comment] 2018-02-22 18:11
@dkelsey when this goes for testing, the setting that Jared specified will need to be set. 
When it goes to PROD, it will need to be in the PROD config

**Comment by dkelsey** [comment] 2018-02-23 23:08
This issues is only relevant to the MOW/OFI:  the issues is caused by a server side call to the OFI API.
The plan  is to move away from the MOW/OFI to the POW.  The POW has no equivalent server side call to the OFI.  Migrating to the POW makes this issue irrelevant.  
I'm moving it to **Closed** for now.

**Closed** 2018-02-23 23:09 UTC
Labels: enhancement
