### ISSUE TITLE
New admins are unable to edit records in all organizations in 1.5.2

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#194] opened 2016-10-06 22:53 UTC
New admin's unable to edit records in all organizations in 1.5.2 (currently in Test and Delivery). I added a new user as an admin in both delivery, test and production. Only in Prod (1.5.1) was the admin able to edit records in organizations other than the one they were added in. 

An admin has to be first created in an organization but they should then appear in all organizations. New admins are only showing under the organization they are created under in 1.5.2. 

@gjlawran @Darv72

**Comment by jrods** [comment] 2016-10-07 17:24
@Mbrownshoes I can't seem to re-create this issue in my env, with using the tagged version of 1.5.1 of the bcgov ext. The new admin has to be added to the org to edit any of the records that belong to that org.

@Mbrownshoes @gjlawran @kfishwick @Darv72 What is the correct behavior that admins should have, with regarding to access of records in other organizations? I think it makes sense having admins restricted to the org(s) they are assigned to and they can only have control within their assigned org(s). I would like to know what the intended behavior is.

**Comment by Mbrownshoes** [comment] 2016-10-07 18:04
@jrods The current behaviour in production (1.5.1) is that once an user is added as an admin for one organization, they had admin access in all orgs. This is an efficient way of giving one of us the ability to edit records across all orgs.  
This behaviour (which is what we want) still works for us in 1.5.1, but is broken in 1.5.2.

**Comment by kfishwick** [comment] 2016-10-11 16:47
@Mbrownshoes  I believe this should happen when an admin user logs in.  Can you grant Jared's idir admin access in cad?

**Comment by Mbrownshoes** [comment] 2016-10-11 16:57
@kfishwick @jrods now has admin access.

**Comment by kfishwick** [comment] 2016-10-11 17:07
Thanks @Mbrownshoes.  One other question, I thought the users had to be granted admin in WebADE, not in ckan.  Did that change?

**Comment by Mbrownshoes** [comment] 2016-10-11 17:35
@kfishwick, yes you're right. I just checked and it is working as it should in delivery - I was able to create an admin by first granting in ADAM and then in ckan. @jrods should not have admin access for all orgs in delivery. Please confirm. In Test new admin's are still not able to edit records in all orgs. I'll try testing with another user.

**Comment by jrods** [comment] 2016-10-11 17:42
I only see my account in the DataBC org and has the admin role. My account is not in the parent org. In my cookies, my edc_auth token is jaresmit_..._EDITOR

**Comment by Mbrownshoes** [comment] 2016-10-11 21:17
did you log out and back in again? Once you do that you should have admin access to all orgs.

**Comment by jrods** [comment] 2016-10-11 21:22
@Mbrownshoes yes, i have admin control now, i can go into any record and edit. My edc_auth cookie also has ADMIN in it.

**Comment by kfishwick** [comment] 2016-10-13 18:11
Matt can you please confirm this is not a bug?

**Comment by Mbrownshoes** [comment] 2016-10-13 20:38
This appears to be working in delivery.

**Comment by kfishwick** [comment] 2016-10-13 20:43
There were no fixes involved here, I think this ticket should be closed as it was user error (users were made admins in CKAN instead of via WebADE).

**Closed** 2016-10-13 22:03 UTC
