### ISSUE TITLE
Authorization error page should tell users to login

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#109] opened 2016-07-05 23:40 UTC
Editors who don't know to login are notifying us that they can't access draft records. We should add a note to the https://cat.data.gov.bc.ca/authorization-error that asks editors to login in to access records in draft.

**Comment by gjlawran** [comment] 2016-07-06 00:28
I believe this a duplicate of https://github.com/bcgov/ckanext-bcgov/issues/89 that is in the V1.3 ready for your testing.

**Closed by gjlawran** 2016-07-06 00:28 UTC
Labels: enhancement
