### ISSUE TITLE
Improve email message sent on state changes

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#89] opened 2016-06-27 22:18 UTC
Linked to CITZEDC-862

**Comment by Mbrownshoes** [comment] 2016-07-06 15:34
The authorization error page still doesn't tell users to login
https://cat.data.gov.bc.ca/authorization-error

**Comment by Mbrownshoes** [comment] 2016-07-06 15:38
@ll911 what's the process for tickets like this that I want to reject? Leave them in code complete or send back to 'in progress'?

**Comment by kfishwick** [comment] 2016-07-06 16:44
Matt the authorization error page is a different issue, not this one.  Is there a problem with the emails?  If so can you please give details?

**Comment by gjlawran** [comment] 2016-07-06 16:56
@Mbrownshoes @kfishwick my bad - it is a duplicate of https://github.com/bcgov/ckanext-bcgov/issues/79 which was not assigned to this release

**Comment by gjlawran** [comment] 2016-07-06 16:58
@kfishwick details of the issue are in JIRA CITZEDC-862

**Comment by kfishwick** [comment] 2016-07-06 17:07
CITZEDC-862 has no new comments.  We fixed that issue & it was delivered.  Do the email templates not match what was provided?

**Closed** 2016-07-12 22:40 UTC
Labels: enhancement
