### ISSUE TITLE
Change Catalogue to use smaller footer

### ISSUE THREAD

**Issue by cnewallbcgov** [bcgov/ckanext-bcgov#488] opened 2018-03-27 18:15 UTC
The currently expanding footer is not required in Catalogue app.

Ref. data.gov.bc.ca - uses the smaller footer.

Leo @l911 knows particulars on what needs to be done.

Smaller footer also needs to apply to Dataset Usage page.

**Comment by jrods** [comment] 2018-03-28 21:43
@ll911 what do you want done on the ckan footer?

do you just want to remove the expanding feature and leave the always visible links, plus the version number, that aren't in the expand view?

**Comment by ll911** [comment] 2018-04-09 19:48
@jrods all details in #127 this is a duplicated issue

**Comment by SteveChapmanBCDX** [comment] 2019-05-29 03:59
Closing as duplicate of #127.

**Closed by SteveChapmanBCDX** 2019-05-29 03:59 UTC
