### ISSUE TITLE
inconsistencies and problem with recline_map_view preview

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#356] opened 2017-06-29 16:39 UTC
The background tiles appear to have changed to stamen map tiles on cat and the ckan demo site but not in cad. Why would cat and cad be different? I didn't notice anything different in the ini files.. 

As mentioned cat and the demo site have the same map preview, although the markers are not showing properly on cat 
![screen shot 2017-06-29 at 9 08 27 am](https://user-images.githubusercontent.com/3362533/27699326-c0abc430-5cae-11e7-9c96-d31527e7540e.png)

but they are on the demo site:
https://demo.ckan.org/dataset/libraries/resource/5b5801b6-9596-4828-8deb-6475368d4974

@ll911 @dkelsey

**Comment by Mbrownshoes** [comment] 2017-06-29 16:48
Looks like a leaflet issue

![screen shot 2017-06-29 at 9 48 08 am](https://user-images.githubusercontent.com/3362533/27699732-1807090a-5cb0-11e7-9273-cddc2031bbca.png)

**Comment by ll911** [comment] 2017-06-29 16:54
Wrong resource URL

https://cat.data.gov.bc.ca/vendor/leaflet/0.7.7/images/marker-shadow.png
https://cat.data.gov.bc.ca/vendor/leaflet/0.7.7/images/marker-icon.png

**Comment by jrods** [comment] 2017-06-29 16:54
what version of ckan is running on cat? cad is running the bcgov-2.5.5 branch now

**Comment by ll911** [comment] 2017-06-29 16:58
2.5.5-bcgov
https://cis-delivery.apps.gov.bc.ca/int/job/bcdc-src-download/100/git-6/

**Comment by jrods** [comment] 2017-06-29 17:10
Looks like the issue is the recline_view.min.js file still using the 0.7.3 path for those images, I'll have to submit a PR to both bcgov fork and ckan core with a fix

**Comment by jrods** [comment] 2017-06-29 17:17
Hold up, recline_view.min.js doesn't exist in the bcgov fork or ckan core. (in ckan: ckanext/reclineview/theme/public/recline_view.min.js) 
I'm confused on why this is. 
@ll911

**Comment by jrods** [comment] 2017-06-29 18:37
@Mbrownshoes @ll911 in cat's ini, are there reclineview.mapview options set? eg: `ckanext.reclineview.mapview.type = mapbox`

**Comment by Mbrownshoes** [comment] 2017-06-29 18:42
ckanext.reclineview.mapview.type = mapbox
odd..

**Comment by ll911** [comment] 2017-06-29 18:45
that's not odd, we are using osm base from mapbox for recline viewer. default mapquest base discontinued when mapquest disabled the public api.

**Comment by Mbrownshoes** [comment] 2017-06-29 18:47
but the actual preview isn't showing mapbox, or the mapbox attribution that is in the ini
ckanext.reclineview.mapview.attribution=Â© <a target=_blank href='https://www.mapbox.com/map-feedback/'>Mapbox</a> Â© <a target=_blank href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>

**Comment by jrods** [comment] 2017-06-29 18:47
@ll911 it's odd that my local and cat both specify mapbox in their ini, yet my local env is using the correct tiles, while cat is not.

**Comment by ll911** [comment] 2017-07-05 20:57
@jrods it has wrong tile because cat references leaflet-0.7.3 resources instead of 0.7.7

**Comment by ll911** [comment] 2017-07-05 23:12
@jrods @dkelsey should be fixed. this is related to old cache, you can see new deployment instruction via [Jenkins PIPELINE](https://gogs.data.gov.bc.ca/bcdc/deployment/src/master/cat/Jenkinsfile)

**Comment by dkelsey** [comment] 2017-09-25 18:19
How do I test this?

**Comment by ll911** [comment] 2017-09-25 18:26
https://catalogue.data.gov.bc.ca/dataset/bc-public-libraries-systems-branches-and-locations-2016/resource/b6a28bfb-580b-4662-9f00-f7189d52fbe6/view/3353cdb5-ef17-4f83-9bf1-c67bfdce3912

**Comment by Mbrownshoes** [comment] 2017-09-25 18:36
Looks like cad, cat and catalogue are all using leaflet 0.7.7 now.

**Closed** 2017-09-25 18:46 UTC
