### ISSUE TITLE
update recline.js to use ESRI leaflet that consumes the BC tilecache 

### ISSUE THREAD

**Issue by Mbrownshoes** [bcgov/ckanext-bcgov#116] opened 2016-07-12 22:24 UTC
MapQuest changed its terms of use for the default leaflet tilecache. fork the reclineview extension and replace the leaflet code in recline.js with the ESRI leaflet code that consumes our own tilecache.

**Comment by Khalegh-H3** [comment] 2016-07-13 16:31
Here is a link to the newly created issue about MapQuest on
ckan-spatial git and some suggested solutions :
https://github.com/ckan/ckanext-spatial/issues/157

**Comment by kfishwick** [comment] 2016-07-13 20:33
Recommendation is to fork ckan version 2.3.4, make the change, and modify deployment to include the forked version.  

@Darv72 and @ll911  please create the fork and we can proceed with the updates.

**Comment by kfishwick** [comment] 2016-07-13 20:34
Note, it appears that this approach will probably have to continue in 2.5, since the same issue occurs there.

**Comment by kfishwick** [comment] 2016-07-13 20:44
Note, this seems to also be logged in CKAN  but they want the recline js provider to update it.

https://github.com/ckan/ckan/issues/3162

**Comment by Darv72** [comment] 2016-07-13 21:47
I've forked the ckan repo into bcgov, the 2.3.4 branch can be found here:

https://github.com/bcgov/ckan/tree/ckan-2.3.4

**Comment by gjlawran** [comment] 2016-07-19 22:05
We are sticking with MapQuest for our 1.4 release - our 1.5 release will allow the inclusion of an attribution statement and URL in our ini.   For our own tile cache the following will be the attribution hyperlink: 
<a href="https://catalogue.data.gov.bc.ca/dataset/a5f40ea5-2b14-4f10-9904-94465e085c7e" target="_blank">Copyright © 2016, Province of British Columbia</a>

**Comment by ll911** [comment] 2016-07-19 22:06
You mean MapBox?

**Comment by gjlawran** [comment] 2016-07-19 22:42
No. - I believe the default is MapQuest hosted tiles built from OSM ....

https://github.com/ckan/ckan/blob/ae2eaa39c2921e53daa439833b3ed267be2a47ad/ckanext/reclineview
/theme/public/vendor/recline/recline.js#L2279

**Comment by kfishwick** [comment] 2016-07-19 22:47
The commit we just merged into your ckan fork includes the ability to customize the map parameters in your ini.  

ckanext.reclineview.mapview.type =
ckanext.reclineview.mapview.mapbox.map_id =
ckanext.reclineview.mapview.mapbox.access_token =
ckanext.reclineview.mapview.attribution =

**Comment by gjlawran** [comment] 2016-07-19 22:57
Ah yes - @ll911  is correct - we are replacing MapQuest hosted tiles with MapBox hosted tiles.  The attribution string specified by MapBox who also uses OSM is specified here
https://www.mapbox.com/help/attribution/

ckanext.reclineview.mapview.attribution = "© <a href='https://www.mapbox.com/map-feedback/'>Mapbox</a> © <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>"

**Comment by kfishwick** [comment] 2016-07-20 00:05
Ok @ll911  will have to add that in the test & prod ini files.  Thanks.

**Comment by gjlawran** [comment] 2016-07-20 19:24
@Khalegh-H3 are you working on including the attribution specified earlier - and ensuring that the target of the attribution hyperlink opens in a  new tab ? It is currently attempting to open within the iframe.

**Comment by kfishwick** [comment] 2016-07-20 19:26
This is just a configuration parameter Greg, Leo can set it to what you want in test.  Including opening in a new tab (html goes in the ini file).

**Comment by Khalegh-H3** [comment] 2016-07-20 19:32
I haven’t done anything in the code for showing attribution target. The fix only includes replacing map tiles through ini configs(including the attribution html) if there are any. Otherwise it uses whatever tiles defined in recline.js. 

As Karen said the attribution text and links can be totally customized using html code in ini file.

**Comment by Mbrownshoes** [comment] 2016-07-21 18:53
When we deploy to test, the ini file is automatically copied over from delivery, thus we need the correct attribution (including fixing the hyperlinks) done in delivery first.

**Comment by gjlawran** [comment] 2016-07-21 20:25
@kfishwick @Khalegh-H3 
In the Delivery ini file - please replace:

`ckanext.reclineview.mapview.attribution=Â© <a target=_blank href='https://www.mapbox.com/map-feedback/'>Mapbox</a> Â© <a href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>
`
with 

`ckanext.reclineview.mapview.attribution=Â© <a target=_blank href='https://www.mapbox.com/map-feedback/'>Mapbox</a> Â© <a target=_blank href='http://www.openstreetmap.org/copyright'>OpenStreetMap</a>`

then @Darv72  will roll to Test.

**Comment by Mbrownshoes** [comment] 2016-07-21 23:43
Woking in test, though the Leaflet attribution still opens within the same page, not in a new tab, as it should.

**Comment by kfishwick** [comment] 2016-07-21 23:59
The leaflet link is not specified in the attribute parameter, I'll have to talk to Khalegh about whether it can be customized.

Thanks,
Karen

**Comment by gjlawran** [comment] 2016-07-22 14:22
Verified in TEST. Will resolve issue with in frame Leaflet attribution in 1.4 or 1.5.

**Comment by gjlawran** [comment] 2016-07-22 17:33
Confirmed in production. Will raise a new issue to resolve problem with Leaflet attribution occurring within iframe.

**Closed by gjlawran** 2016-07-22 17:33 UTC
Labels: bug, enhancement

**Comment by ll911** [comment] 2016-07-22 17:35
Can you close the milestone?

Sent from Mobile




On Fri, Jul 22, 2016 at 10:34 AM -0700, "Greg Lawrance" <notifications@github.com<mailto:notifications@github.com>> wrote:


Confirmed in production. Will raise a new issue to resolve problem with Leaflet attribution occurring within iframe.

-
