### ISSUE TITLE
BCDC - "Next: Add Data" button - unexpected behaviour when adding a new geographic dataset

### ISSUE THREAD

**Issue by mhoole** [bcgov/ckanext-bcgov#681] opened 2019-01-03 20:06 UTC
# ENV
`PROD`, `CAT`, `CAD`

# TESTCASE
* using Firefox (Quantum 64.0)
* Step 1.  Create a Geographic Dataset
* Step 2.  Enter all required metadata details
* Step 3.  Save the dataset (without adding any resources)
* Step 4.  Click the wrench to edit
* Step 5.  scroll to the bottom of the metadata page and hit "Next: Add Data"

# EXPECTED
* After clicking "Next: Add Data" you should be taken to the resources page.

# ACTUAL
* Instead, the record saves again and exits the edit session.

**Comment by mhoole** [comment] 2019-01-08 00:00
20190107 this still appears to be an issue in Test https://cat.data.gov.bc.ca/

**Comment by mdunhamwilkie** [comment] 2019-01-25 14:45
@jachurchill or @BrandonSharratt , this may have been fixed.  Please check

**Comment by jachurchill** [comment] 2019-01-31 18:05
@mdunhamwilkie so this one took me a little while to track down exactly, I ended up checking out the old master branch from before we made any changes and confirmed it was old functionality so it wasn't effected by my changes to the button. Anyways the main crux turns out to be that the function that handles this is not the same one that handles when it's a new dataset and the submission doesn't work the same. Basically when doing the update the function can't tell what button you used to do the save so the best solution I could find was just to remove the "Next: Add Data" button and only have save because there isn't any benefit in 2 buttons that do the same thing. They can still add resources by just clicking the resources tab at the top of the form. Does this work for you or do you have any questions?

**Comment by SteveChapmanBCDX** [comment] 2019-05-24 23:31
Tested in TEST - the "Next: Add Data" button no longer appears.  
I need to test this in PROD with someone who can delete the draft dataset.

**Comment by mdunhamwilkie** [comment] 2019-05-26 14:31
@SteveChapmanBCDX and @jachurchill , the Save button should take you to where the "Next: Add Data" button used to take you - i.e.., to the form that has manage and add resources, leaving you in edit mode. Currently in the modified version in Test it takes you out of edit mode, you go back to the main page and have to reenter edit mode to add the resource. This is inconvenient.

**Comment by SteveChapmanBCDX** [comment] 2019-05-28 19:34
@jachurchill - I reviewed this issue with @mdunhamwilkie.  @mdunhamwilkie is satisfied with the current behaviour of the production website.  Accordingly, we do NOT need to add these code changes to the code base.

This code change does not appear to have been merged into DEV or MASTER.  If I am incorrect, those changes need to be reverted.

**Comment by SteveChapmanBCDX** [comment] 2019-05-30 17:52
@mdunhamwilkie - Ready for you to test in cati.

**Comment by SteveChapmanBCDX** [comment] 2019-06-04 19:41
Reviewed and tested with @mdunhamwilkie.  Closing ticket as complete.

**Closed by SteveChapmanBCDX** 2019-06-04 19:41 UTC
Labels: bug
